package com.google.sitebricks.example;

import com.google.sitebricks.At;
import com.google.sitebricks.Show;

/**
 * Example of a page rendered with a different templating technology
 * (other than sitebricks).
 */
@At("/template/mvel") @Show("MvelTemplateExample.mvel")
public class MvelTemplateExample {
  private final String message = "hey hey! Generated by MVEL templates dynamically =)";

  public String getMessage() {
    return message;
  }
}
